import { v4 as uuidv4 } from "uuid";
export const GET = async () => {
  return Response.json([
    {
      id: "1",
      img: "/image/sale/sale1.webp",
      ghest: "ghest",
      toman: "toman",
      ghestPayment: "sale.ghestpayment1",
      brand: "sale.brand1",
      information: "sale.information1",
      mainPayment: "sale.mainpayment1",
      darsad: "sale.darsad1",
      salePayment: "sale.salepayment1",
    },
    {
      id: "2",
      img: "/image/sale/sale2.webp",
      ghest: "ghest",
      toman: "toman",
      ghestPayment: "sale.ghestpayment2",
      brand: "sale.brand2",
      information: "sale.information2",
      mainPayment: "sale.mainpayment2",
      darsad: "sale.darsad2",
      salePayment: "sale.salepayment2",
    },
    {
      id: "3",
      img: "/image/sale/sale3.webp",
      ghest: "ghest",
      toman: "toman",
      ghestPayment: "sale.ghestpayment3",
      brand: "sale.brand3",
      information: "sale.information3",
      mainPayment: "sale.mainpayment3",
      darsad: "sale.darsad3",
      salePayment: "sale.salepayment3",
    },
    {
      id: "4",
      img: "/image/sale/sale4.webp",
      ghest: "ghest",
      toman: "toman",
      ghestPayment: "sale.ghestpayment4",
      brand: "sale.brand4",
      information: "sale.information4",
      mainPayment: "sale.mainpayment4",
      darsad: "sale.darsad4",
      salePayment: "sale.salepayment4",
    },
    {
      id: "5",
      img: "/image/sale/sale5.webp",
      ghest: "ghest",
      toman: "toman",
      ghestPayment: "sale.ghestpayment5",
      brand: "sale.brand5",
      information: "sale.information5",
      mainPayment: "sale.mainpayment5",
      darsad: "sale.darsad5",
      salePayment: "sale.salepayment5",
    },
    {
      id: "6",
      img: "/image/sale/sale6.webp",
      ghest: "ghest",
      toman: "toman",
      ghestPayment: "sale.ghestpayment6",
      brand: "sale.brand6",
      information: "sale.information6",
      mainPayment: "sale.mainpayment6",
      darsad: "sale.darsad6",
      salePayment: "sale.salepayment6",
    },
    {
      id: "7",
      img: "/image/sale/sale7.webp",
      ghest: "ghest",
      toman: "toman",
      ghestPayment: "sale.ghestpayment7",
      brand: "sale.brand7",
      information: "sale.information7",
      mainPayment: "sale.mainpayment7",
      darsad: "sale.darsad7",
      salePayment: "sale.salepayment7",
    },
    {
      id: "8",
      img: "/image/sale/sale8.webp",
      ghest: "ghest",
      toman: "toman",
      ghestPayment: "sale.ghestpayment8",
      brand: "sale.brand8",
      information: "sale.information8",
      salePayment: "sale.salepayment8",
    },
    {
      id: "9",
      img: "/image/sale/sale9.webp",
      ghest: "ghest",
      toman: "toman",
      ghestPayment: "sale.ghestpayment9",
      brand: "sale.brand9",
      information: "sale.information9",
      mainPayment: "sale.mainpayment9",
      darsad: "sale.darsad9",
      salePayment: "sale.salepayment9",
    },
    {
      id: "10",
      img: "/image/sale/sale10.webp",
      ghest: "ghest",
      toman: "toman",
      ghestPayment: "sale.ghestpayment10",
      brand: "sale.brand10",
      information: "sale.information10",
      mainPayment: "sale.mainpayment10",
      darsad: "sale.darsad10",
      salePayment: "sale.salepayment10",
    },
  ]);
};
